"""add expires_at to password otp

Revision ID: 01b144eaf71d
Revises: be7400a8d7ab
Create Date: 2026-09-30 14:18:10.058290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b144eaf71d'
down_revision: Union[str, Sequence[str], None] = 'be7400a8d7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_otp_id'), 'password_reset_otp', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_otp_user_id'), 'password_reset_otp', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_otp_user_id'), table_name='password_reset_otp')
    op.drop_index(op.f('ix_password_reset_otp_id'), table_name='password_reset_otp')
    op.drop_table('password_reset_otp')
    # ### end Alembic commands ###
