"""add variant_id to cart_items

Revision ID: 0a2aab7072e6
Revises: 563834fc56b6
Create Date: 2026-07-25 18:02:44.772330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2aab7072e6'
down_revision: Union[str, Sequence[str], None] = '563834fc56b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'variant_id')
    # ### end Alembic commands ###
