"""add customer info fields to order

Revision ID: 4581959389db
Revises: 4392f2045fac
Create Date: 2026-07-28 17:09:25.402413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4581959389db'
down_revision: Union[str, Sequence[str], None] = '4392f2045fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('postal_code', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('paid', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'transaction_id')
    op.drop_column('orders', 'paid')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'postal_code')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    # ### end Alembic commands ###
